apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: finflow
type: Opaque
stringData:
  users: users_pw
  wallet: wallet_pw
  payment: payment_pw
  audit: audit_pw
  postgres: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: finflow
type: Opaque
stringData:
  password: admin
